# Generated by Django 2.0.5 on 2018-09-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreClase', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Clase',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDominio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Dominio',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreFamilia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Familia',
            },
        ),
        migrations.CreateModel(
            name='Filo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreFilo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Filo',
            },
        ),
        migrations.CreateModel(
            name='Fosil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoFosil', models.CharField(max_length=25)),
                ('NombreEspecie', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('ClaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Clase')),
                ('DominioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Dominio')),
                ('FamiliaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Familia')),
                ('FiloID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Filo')),
            ],
            options={
                'db_table': 'Fosil',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreGenero', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreOrden', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Reino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreReino', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Reino',
            },
        ),
        migrations.AddField(
            model_name='fosil',
            name='GeneroID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Genero'),
        ),
        migrations.AddField(
            model_name='fosil',
            name='OrdenID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Orden'),
        ),
        migrations.AddField(
            model_name='fosil',
            name='ReinoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosil.Reino'),
        ),
    ]
