# Generated by Django 2.0.5 on 2018-09-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosil',
            name='ClaseID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Clase'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='DominioID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Dominio'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='FamiliaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Familia'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='FiloID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Filo'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='GeneroID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Genero'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='OrdenID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Orden'),
        ),
        migrations.AlterField(
            model_name='fosil',
            name='ReinoID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fosil.Reino'),
        ),
    ]
